### ISSUE TITLE
Crash during mopidy start up

### ISSUE THREAD

**Issue by vorou** [sibuser/mopidy-vkontakte#10]
Mopidy 0.19.4, just installed the plugin from pip. Here's the output:

```
pi@raspberrypi ~ $ mopidy
INFO Starting Mopidy 0.19.4
INFO Loading config from: builtin defaults, /etc/xdg/mopidy/mopidy.conf, /home/pi/.config/mopidy/mopidy.conf, command line options
INFO Enabled extensions: mpd, softwaremixer, http, vkontakte, stream
INFO Disabled extensions: local
INFO Starting Mopidy mixer: SoftwareMixer
INFO Mixing using GStreamer software mixing
INFO Starting Mopidy audio
INFO Starting Mopidy backends: StreamBackend, VKBackend
INFO Audio output set to "autoaudiosink"
INFO Login as krubi@k66.ru
INFO Mopidy uses Vkontakte Music
INFO Fetching a playlist "all_songs" from VKontakte
INFO Fetching a playlist "acoustic•folk" from VKontakte
INFO Fetching a playlist "SYPER-KA4" from VKontakte
INFO Fetching a playlist "bd22" from VKontakte
INFO Fetching a playlist "dec10" from VKontakte
INFO Fetching a playlist "saintpsad" from VKontakte
INFO Fetching a playlist "romantic porno" from VKontakte
INFO Fetching a playlist "toplayer 09/04/10" from VKontakte
INFO Fetching a playlist "dubstep" from VKontakte
INFO Loaded 9 VKontakte playlist(s)
ERROR Uncaught exception
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 272, in run
backends = self.start_backends(config, backend_classes, audio)
File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 343, in start_backends
config=config, audio=audio).proxy()
File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
obj = cls(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/actor.py", line 24, in __init__
self.playlists = VKPlaylistsProvider(backend=self)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/playlists.py", line 18, in __init__
self.refresh()
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/playlists.py", line 79, in refresh
self.backend.library.generate_folders(self.all_lists)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 29, in generate_folders
self.add_to_vfs(self.new_folder(name.capitalize(), [name]))
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 33, in new_folder
uri=self.generate_uri(path),
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 100, in generate_uri
return 'vkontakte:directory:%s' % urllib.quote('/'.join(path))
File "/usr/lib/python2.7/urllib.py", line 1268, in quote
return ''.join(map(quoter, s))
KeyError: u'\u2022'
INFO Stopping Mopidy frontends
INFO Stopping Mopidy core
INFO Stopping Mopidy backends
INFO Stopping Mopidy audio
INFO Stopping Mopidy mixer
pi@raspberrypi ~ $ mopidy
INFO Starting Mopidy 0.19.4
INFO Loading config from: builtin defaults, /etc/xdg/mopidy/mopidy.conf, /home/pi/.config/mopidy/mopidy.conf, command line options
INFO Enabled extensions: mpd, softwaremixer, http, vkontakte, stream
INFO Disabled extensions: local
INFO Starting Mopidy mixer: SoftwareMixer
INFO Mixing using GStreamer software mixing
INFO Starting Mopidy audio
INFO Starting Mopidy backends: StreamBackend, VKBackend
INFO Audio output set to "autoaudiosink"
INFO Mopidy uses Vkontakte Music
INFO Fetching a playlist "all_songs" from VKontakte
INFO Fetching a playlist "acoustic•folk" from VKontakte
INFO Fetching a playlist "SYPER-KA4" from VKontakte
INFO Fetching a playlist "bd22" from VKontakte
INFO Fetching a playlist "dec10" from VKontakte
INFO Fetching a playlist "saintpsad" from VKontakte
INFO Fetching a playlist "romantic porno" from VKontakte
INFO Fetching a playlist "toplayer 09/04/10" from VKontakte
INFO Fetching a playlist "dubstep" from VKontakte
INFO Loaded 9 VKontakte playlist(s)
ERROR Uncaught exception
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 272, in run
backends = self.start_backends(config, backend_classes, audio)
File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 343, in start_backends
config=config, audio=audio).proxy()
File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
obj = cls(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/actor.py", line 24, in __init__
self.playlists = VKPlaylistsProvider(backend=self)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/playlists.py", line 18, in __init__
self.refresh()
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/playlists.py", line 79, in refresh
self.backend.library.generate_folders(self.all_lists)
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 29, in generate_folders
self.add_to_vfs(self.new_folder(name.capitalize(), [name]))
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 33, in new_folder
uri=self.generate_uri(path),
File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/library.py", line 100, in generate_uri
return 'vkontakte:directory:%s' % urllib.quote('/'.join(path))
File "/usr/lib/python2.7/urllib.py", line 1268, in quote
return ''.join(map(quoter, s))
KeyError: u'\u2022'
INFO Stopping Mopidy frontends
INFO Stopping Mopidy core
INFO Stopping Mopidy backends
INFO Stopping Mopidy audio
INFO Stopping Mopidy mixer
```

**Comment by sibuser** [comment]
Hi! 
Thanks for you issue. Right now I'm on vacation and will be back in couple of weeks.

**Comment by sibuser** [comment]
That problem happens because of cyrillic symbols in names . will be fixed today.

**Comment by sibuser** [comment]
Fixed.
