### ISSUE TITLE
ValueError: unknown url type: /login?act=authcheck_code&hash=...

### ISSUE THREAD

**Issue by notpushkin** [sibuser/mopidy-vkontakte#16]
``` py
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 274, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 352, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/actor.py", line 21, in __init__
    self.session = VKSession(config=self.config)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 73, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 101, in login
    url = self.give_access(doc, opener)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 138, in give_access
    response = opener.open(parser.url, urllib.urlencode(parser.params))
  File "/usr/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /login?act=authcheck_code&hash={...actual hash here...}
```

Any ideas?

**Comment by itJunky** [comment]
Have same error
