### ISSUE TITLE
Mopidy crashes

### ISSUE THREAD

**Issue by goodmind** [sibuser/mopidy-vkontakte#17]
```
ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 274, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 352, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/actor.py", line 21, in __init__
    self.session = VKSession(config=self.config)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 73, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 103, in login
    answer = dict(self.split_key_value(kv_pair) for kv_pair in pairs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 103, in <genexpr>
    answer = dict(self.split_key_value(kv_pair) for kv_pair in pairs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_vkontakte/session.py", line 110, in split_key_value
    return kv[0], kv[1]
IndexError: list index out of range
```

**Comment by TwoLeaves** [comment]
Also getting this issue. With or without client_id.
